"""
Hand-curated, verified World Cup trivia questions for the NCC contest.
All facts cross-checked against FIFA records.
Mix of templates: text, image_face (covered/pixelated faces), image_jersey, image_trophy, composition.
Difficulty: medium-to-hard (not too easy).
"""

# Wikipedia thumbnail URLs for player images (free + stable).
P = {
    "messi":   "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Lionel_Messi_WC2022.jpg/320px-Lionel_Messi_WC2022.jpg",
    "ronaldo_br": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Ronaldo_-_Brazil.jpg/320px-Ronaldo_-_Brazil.jpg",
    "maradona": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Maradona-Mundial_86_con_la_copa.JPG/320px-Maradona-Mundial_86_con_la_copa.JPG",
    "pele":    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Pele_with_trophy.jpg/320px-Pele_with_trophy.jpg",
    "zidane":  "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Zinedine_Zidane_2008.jpg/320px-Zinedine_Zidane_2008.jpg",
    "klose":   "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Miroslav_Klose_-_Polish_Bayer.jpg/320px-Miroslav_Klose_-_Polish_Bayer.jpg",
    "mbappe":  "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Mbappe_27sept2017.jpg/320px-Mbappe_27sept2017.jpg",
    "cr7":     "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Cristiano_Ronaldo_2018.jpg/320px-Cristiano_Ronaldo_2018.jpg",
    "beckenbauer": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Bundesarchiv_B_145_Bild-F040220-0020%2C_K%C3%B6ln%2C_F.C._Bayern_M%C3%BCnchen_in_M%C3%BCngersdorfer_Stadion.jpg/320px-Bundesarchiv_B_145_Bild-F040220-0020%2C_K%C3%B6ln%2C_F.C._Bayern_M%C3%BCnchen_in_M%C3%BCngersdorfer_Stadion.jpg",
    "salah":   "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Salah_2018.jpg/320px-Salah_2018.jpg",
    "lampard": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Frank_Lampard_2017.jpg/320px-Frank_Lampard_2017.jpg",
    "trophy":  "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/FIFA_World_Cup_Trophy_2014_001.jpg/320px-FIFA_World_Cup_Trophy_2014_001.jpg",
    "jules_rimet": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Jules_Rimet_Cup.jpg/320px-Jules_Rimet_Cup.jpg",
    "iniesta": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Andres_Iniesta_-_Spain_vs._USA_2011.jpg/320px-Andres_Iniesta_-_Spain_vs._USA_2011.jpg",
    "modric":  "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/2018-08-15_FIFA_Best_Football_Awards-_Modri%C4%87.jpg/320px-2018-08-15_FIFA_Best_Football_Awards-_Modri%C4%87.jpg",
    "neuer":   "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Manuel_Neuer_2017.jpg/320px-Manuel_Neuer_2017.jpg",
    "buffon":  "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Gianluigi_Buffon_2018.jpg/320px-Gianluigi_Buffon_2018.jpg",
    "neymar":  "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Bra-Cos_%287%29.jpg/320px-Bra-Cos_%287%29.jpg",
    "kane":    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Harry_Kane_2017.jpg/320px-Harry_Kane_2017.jpg",
    "suarez":  "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Luis_Suarez_with_Liverpool.jpg/320px-Luis_Suarez_with_Liverpool.jpg",
    "lewandowski": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Robert_Lewandowski_2018.jpg/320px-Robert_Lewandowski_2018.jpg",
    "benzema": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Karim_Benzema_2018_%28cropped%29.jpg/320px-Karim_Benzema_2018_%28cropped%29.jpg",
    "kaka":    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Kaka_2014.jpg/320px-Kaka_2014.jpg",
    "ronaldinho": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Ronaldinho_2008.jpg/320px-Ronaldinho_2008.jpg",
    "platini": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Michel_Platini_-_French_FA_-_27-09-2007.jpg/320px-Michel_Platini_-_French_FA_-_27-09-2007.jpg",
    "ramos":   "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Sergio_Ramos_2018.jpg/320px-Sergio_Ramos_2018.jpg",
    "owen":    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Michael_Owen_in_2009.jpg/320px-Michael_Owen_in_2009.jpg",
    "beckham": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/David_Beckham.jpg/320px-David_Beckham.jpg",
    "henry":   "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Thierry_Henry_2017.jpg/320px-Thierry_Henry_2017.jpg",
    "drogba":  "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Didier_Drogba_2018.jpg/320px-Didier_Drogba_2018.jpg",
}


def q(question_en, question_ar, choices_en, choices_ar, correct_index, **kw):
    return {
        "question": question_en,
        "question_ar": question_ar,
        "choices": choices_en,
        "choices_ar": choices_ar,
        "correct_index": correct_index,
        **kw,
    }


SEED_QUESTIONS = [
    # ===== TOURNAMENTS =====
    q("In which year was the first FIFA World Cup held?",
      "في أي عام أُقيمت أول بطولة لكأس العالم؟",
      ["1928", "1930", "1934", "1938"],
      ["١٩٢٨", "١٩٣٠", "١٩٣٤", "١٩٣٨"], 1,
      type="text", difficulty="medium", category="tournaments",
      explanation_ar="أُقيمت أول بطولة كأس العالم عام ١٩٣٠ في الأوروغواي."),
    q("Which country hosted the first FIFA World Cup?",
      "أي دولة استضافت أول بطولة كأس عالم؟",
      ["Brazil", "Italy", "Uruguay", "France"],
      ["البرازيل", "إيطاليا", "الأوروغواي", "فرنسا"], 2,
      type="text", difficulty="medium", category="tournaments",
      explanation_ar="استضافت الأوروغواي البطولة الأولى وفازت بها."),
    q("Which country has won the most World Cup titles?",
      "أكثر منتخب فاز ببطولة كأس العالم؟",
      ["Germany", "Italy", "Argentina", "Brazil"],
      ["ألمانيا", "إيطاليا", "الأرجنتين", "البرازيل"], 3,
      type="text", difficulty="medium", category="tournaments",
      explanation_ar="البرازيل بـ ٥ ألقاب (١٩٥٨، ١٩٦٢، ١٩٧٠، ١٩٩٤، ٢٠٠٢)."),
    q("Who won the 2022 FIFA World Cup in Qatar?",
      "من فاز ببطولة كأس العالم ٢٠٢٢ في قطر؟",
      ["France", "Argentina", "Brazil", "Croatia"],
      ["فرنسا", "الأرجنتين", "البرازيل", "كرواتيا"], 1,
      type="text", difficulty="medium", category="tournaments",
      explanation_ar="فازت الأرجنتين بركلات الترجيح على فرنسا (٤-٢) بعد ٣-٣."),
    q("Which year did Spain win their only World Cup title?",
      "في أي عام فازت إسبانيا بلقبها الوحيد لكأس العالم؟",
      ["2006", "2010", "2014", "2018"],
      ["٢٠٠٦", "٢٠١٠", "٢٠١٤", "٢٠١٨"], 1,
      type="text", difficulty="medium", category="tournaments",
      explanation_ar="فازت إسبانيا في جنوب أفريقيا ٢٠١٠ بهدف إنييستا في الوقت الإضافي."),
    q("Which two countries co-hosted the 2002 World Cup?",
      "أي دولتان استضافتا كأس العالم ٢٠٠٢ بشكل مشترك؟",
      ["China & Japan", "Japan & South Korea", "South Korea & Thailand", "Japan & Hong Kong"],
      ["الصين واليابان", "اليابان وكوريا الجنوبية", "كوريا الجنوبية وتايلاند", "اليابان وهونغ كونغ"], 1,
      type="text", difficulty="medium", category="tournaments",
      explanation_ar="أول بطولة كأس عالم تُقام في آسيا، وأول مشاركة في الاستضافة."),
    q("How many countries will play in the 2026 World Cup?",
      "كم منتخب سيشارك في كأس العالم ٢٠٢٦؟",
      ["32", "40", "48", "64"],
      ["٣٢", "٤٠", "٤٨", "٦٤"], 2,
      type="text", difficulty="medium", category="tournaments",
      explanation_ar="نسخة ٢٠٢٦ هي الأولى بـ ٤٨ منتخباً في ١٢ مجموعة."),
    q("Which 3 countries are co-hosting the 2026 FIFA World Cup?",
      "أي ٣ دول تستضيف كأس العالم ٢٠٢٦ بشكل مشترك؟",
      ["USA, Canada, Mexico", "USA, Mexico, Cuba", "Canada, Mexico, Brazil", "USA, Argentina, Canada"],
      ["أمريكا، كندا، المكسيك", "أمريكا، المكسيك، كوبا", "كندا، المكسيك، البرازيل", "أمريكا، الأرجنتين، كندا"], 0,
      type="text", difficulty="medium", category="tournaments"),
    q("Which country won the World Cup three times in a row in 1934, 1938 (and lost final 1950)?",
      "أي منتخب فاز ببطولتي ١٩٣٤ و١٩٣٨ متتاليتين؟",
      ["Germany", "Brazil", "Italy", "Argentina"],
      ["ألمانيا", "البرازيل", "إيطاليا", "الأرجنتين"], 2,
      type="text", difficulty="hard", category="tournaments",
      explanation_ar="فازت إيطاليا في النسختين المتتاليتين بقيادة فيتوريو بوتزو."),
    q("Which World Cup is famous as 'the Maracanazo'?",
      "أي بطولة كأس عالم اشتُهرت بـ«ماراكانازو»؟",
      ["1930", "1950", "1962", "1978"],
      ["١٩٣٠", "١٩٥٠", "١٩٦٢", "١٩٧٨"], 1,
      type="text", difficulty="hard", category="tournaments",
      explanation_ar="نهائي ١٩٥٠ عندما هزمت الأوروغواي البرازيل في الماراكانا ٢-١."),

    # ===== PLAYERS - TEXT =====
    q("Who is the all-time top scorer in World Cup history?",
      "من هو أكثر هداف في تاريخ كأس العالم؟",
      ["Pelé", "Miroslav Klose", "Ronaldo (Brazil)", "Gerd Müller"],
      ["بيليه", "ميروسلاف كلوزه", "رونالدو (البرازيل)", "غيرد مولر"], 1,
      type="text", difficulty="medium", category="players",
      explanation_ar="كلوزه برصيد ١٦ هدفاً في ٤ بطولات (٢٠٠٢-٢٠١٤)."),
    q("Who won the Golden Boot at the 2022 World Cup?",
      "من فاز بالحذاء الذهبي في مونديال ٢٠٢٢؟",
      ["Lionel Messi", "Kylian Mbappé", "Olivier Giroud", "Julián Álvarez"],
      ["ليونيل ميسي", "كيليان مبابي", "أوليفييه جيرو", "خوليان ألفاريز"], 1,
      type="text", difficulty="medium", category="players",
      explanation_ar="مبابي بـ ٨ أهداف، شامل هاتريك في النهائي."),
    q("Who scored the famous 'Hand of God' goal in 1986?",
      "من سجل هدف «يد الله» الشهير عام ١٩٨٦؟",
      ["Jorge Burruchaga", "Diego Maradona", "Mario Kempes", "Daniel Passarella"],
      ["خورخي بوروتشاغا", "دييغو مارادونا", "ماريو كيمبس", "دانيل باساريلا"], 1,
      type="text", difficulty="medium", category="players",
      explanation_ar="مارادونا ضد إنجلترا في ربع نهائي ١٩٨٦ بالمكسيك."),
    q("Who is the only player to win the World Cup three times as a player?",
      "من اللاعب الوحيد الذي فاز بكأس العالم ٣ مرات كلاعب؟",
      ["Pelé", "Diego Maradona", "Franz Beckenbauer", "Cafu"],
      ["بيليه", "دييغو مارادونا", "فرانز بيكنباور", "كافو"], 0,
      type="text", difficulty="medium", category="players",
      explanation_ar="بيليه فاز عام ١٩٥٨، ١٩٦٢، و١٩٧٠ مع البرازيل."),
    q("Who headbutted Marco Materazzi in the 2006 World Cup final?",
      "من نطح ماركو ماتيراتزي في نهائي كأس العالم ٢٠٠٦؟",
      ["Patrick Vieira", "Thierry Henry", "Zinedine Zidane", "Lilian Thuram"],
      ["باتريك فييرا", "تييري هنري", "زين الدين زيدان", "ليليان توران"], 2,
      type="text", difficulty="medium", category="players",
      explanation_ar="زيدان في آخر مباراة احترافية له، طُرد ثم خسرت فرنسا بركلات الترجيح."),
    q("How old was Pelé when he won his first World Cup in 1958?",
      "كم كان عمر بيليه عند فوزه بأول كأس عالم ١٩٥٨؟",
      ["17", "19", "21", "23"],
      ["١٧", "١٩", "٢١", "٢٣"], 0,
      type="text", difficulty="hard", category="players",
      explanation_ar="١٧ سنة و٢٤٩ يوماً — أصغر فائز بالكأس على الإطلاق."),
    q("Who scored the winning goal for Spain in the 2010 World Cup final?",
      "من سجل هدف الفوز لإسبانيا في نهائي ٢٠١٠؟",
      ["David Villa", "Xavi", "Andrés Iniesta", "Sergio Ramos"],
      ["دافيد فيا", "تشافي", "أندريس إنييستا", "سيرخيو راموس"], 2,
      type="text", difficulty="medium", category="players",
      explanation_ar="إنييستا في الدقيقة ١١٦ من الوقت الإضافي ضد هولندا."),
    q("Which goalkeeper won the Golden Glove at the 2014 World Cup?",
      "أي حارس فاز بالقفاز الذهبي في مونديال ٢٠١٤؟",
      ["Iker Casillas", "Keylor Navas", "Manuel Neuer", "Tim Howard"],
      ["إيكر كاسياس", "كيلور نافاس", "مانويل نوير", "تيم هاورد"], 2,
      type="text", difficulty="medium", category="players",
      explanation_ar="مانويل نوير، أحد أبطال فوز ألمانيا بالكأس في البرازيل."),
    q("Who scored a hat-trick in the 1966 World Cup final?",
      "من سجل هاتريك في نهائي كأس العالم ١٩٦٦؟",
      ["Bobby Charlton", "Geoff Hurst", "Eusébio", "Pelé"],
      ["بوبي تشارلتون", "جيوف هيرست", "يوسيبيو", "بيليه"], 1,
      type="text", difficulty="hard", category="players",
      explanation_ar="جيوف هيرست، اللاعب الوحيد الذي سجل هاتريك في نهائي حتى اليوم."),
    q("Who won the Golden Ball (best player) at the 2022 World Cup?",
      "من فاز بالكرة الذهبية (أفضل لاعب) في مونديال ٢٠٢٢؟",
      ["Kylian Mbappé", "Luka Modrić", "Lionel Messi", "Antoine Griezmann"],
      ["كيليان مبابي", "لوكا مودريتش", "ليونيل ميسي", "أنطوان غريزمان"], 2,
      type="text", difficulty="medium", category="players",
      explanation_ar="ميسي توّج البطولة بأفضل لاعب وقاد الأرجنتين للقب."),
    q("Who was the youngest scorer in a World Cup final?",
      "من أصغر هداف في نهائي كأس العالم؟",
      ["Mbappé", "Pelé", "Owen", "Messi"],
      ["مبابي", "بيليه", "أوين", "ميسي"], 1,
      type="text", difficulty="hard", category="players",
      explanation_ar="بيليه، عمر ١٧ عاماً و٢٤٩ يوماً في نهائي ١٩٥٨."),
    q("Who is the captain who lifted the trophy for Spain in 2010?",
      "من القائد الذي رفع كأس العالم لإسبانيا في ٢٠١٠؟",
      ["Xavi", "Iker Casillas", "Carles Puyol", "Sergio Ramos"],
      ["تشافي", "إيكر كاسياس", "كارلس بويول", "سيرخيو راموس"], 1,
      type="text", difficulty="medium", category="players"),
    q("Who scored the fastest goal in World Cup history (11 seconds, 2002)?",
      "من سجل أسرع هدف في تاريخ كأس العالم (١١ ثانية، ٢٠٠٢)؟",
      ["Ronaldo (Brazil)", "Hakan Şükür", "Michael Owen", "Rivaldo"],
      ["رونالدو (البرازيل)", "هاكان شوكور", "مايكل أوين", "ريفالدو"], 1,
      type="text", difficulty="hard", category="players",
      explanation_ar="شوكور (تركيا) ضد كوريا الجنوبية في مباراة المركز الثالث ٢٠٠٢."),
    q("Who was the captain when Germany won the 2014 World Cup?",
      "من قائد ألمانيا عند فوزها بمونديال ٢٠١٤؟",
      ["Bastian Schweinsteiger", "Philipp Lahm", "Manuel Neuer", "Thomas Müller"],
      ["شفاينشتايغر", "فيليب لام", "نوير", "مولر"], 1,
      type="text", difficulty="medium", category="players"),
    q("Who scored the winning goal in the 2014 World Cup final?",
      "من سجل هدف الفوز في نهائي مونديال ٢٠١٤؟",
      ["Thomas Müller", "Mario Götze", "André Schürrle", "Bastian Schweinsteiger"],
      ["توماس مولر", "ماريو غوتزه", "أندريه شورله", "شفاينشتايغر"], 1,
      type="text", difficulty="medium", category="players",
      explanation_ar="غوتزه بديلاً في الدقيقة ١١٣ ضد الأرجنتين بميراكانا."),

    # ===== RECORDS =====
    q("Who has played the most matches in World Cup history?",
      "من شارك بأكبر عدد مباريات في كأس العالم؟",
      ["Cristiano Ronaldo", "Lionel Messi", "Lothar Matthäus", "Paolo Maldini"],
      ["كريستيانو رونالدو", "ليونيل ميسي", "لوتار ماتيوس", "باولو مالديني"], 1,
      type="text", difficulty="hard", category="records",
      explanation_ar="ميسي تجاوز ماتيوس في مونديال ٢٠٢٢ ليصبح صاحب الرقم القياسي بـ ٢٦ مباراة."),
    q("What is the largest victory margin ever in a World Cup match?",
      "ما هو أكبر فارق فوز في مباراة كأس عالم؟",
      ["7 goals", "8 goals", "9 goals", "10 goals"],
      ["٧ أهداف", "٨ أهداف", "٩ أهداف", "١٠ أهداف"], 2,
      type="text", difficulty="hard", category="records",
      explanation_ar="المجر هزمت كوريا الجنوبية ٩-٠ عام ١٩٥٤، ويوغوسلافيا هزمت زائير ٩-٠ عام ١٩٧٤."),
    q("Most World Cup titles by a coach?",
      "أكثر بطولات كأس عالم لمدرب؟",
      ["1", "2", "3", "4"],
      ["١", "٢", "٣", "٤"], 1,
      type="text", difficulty="hard", category="records",
      explanation_ar="فيتوريو بوتزو (إيطاليا) فاز ببطولتي ١٩٣٤ و١٩٣٨ متتاليتين."),
    q("In which year was a World Cup not held due to WWII?",
      "في أي سنة لم تُقم بطولة كأس العالم بسبب الحرب العالمية الثانية؟",
      ["1942 only", "1942 and 1946", "1946 only", "1940 and 1944"],
      ["١٩٤٢ فقط", "١٩٤٢ و ١٩٤٦", "١٩٤٦ فقط", "١٩٤٠ و ١٩٤٤"], 1,
      type="text", difficulty="hard", category="records",
      explanation_ar="أُلغيت بطولتا ١٩٤٢ و١٩٤٦ بسبب الحرب العالمية الثانية."),
    q("Which country has the longest unbeaten run in World Cup matches?",
      "أي منتخب يملك أطول سلسلة دون هزيمة في كأس العالم؟",
      ["Italy", "Brazil", "Germany", "Spain"],
      ["إيطاليا", "البرازيل", "ألمانيا", "إسبانيا"], 0,
      type="text", difficulty="hard", category="records",
      explanation_ar="إيطاليا حافظت على شباكها نظيفة ٥٥٠ دقيقة في ١٩٩٠."),
    q("Which goalkeeper has the most clean sheets in World Cup history?",
      "أي حارس لديه أكثر شباك نظيفة في كأس العالم؟",
      ["Peter Shilton", "Manuel Neuer", "Gianluigi Buffon", "Iker Casillas"],
      ["بيتر شيلتون", "مانويل نوير", "بوفون", "كاسياس"], 0,
      type="text", difficulty="hard", category="records",
      explanation_ar="شيلتون و فابيان بارتيز يتقاسمان الرقم بـ ١٠ مباريات نظيفة."),
    q("Which country was the first non-European/South American team to host?",
      "أول دولة خارج أوروبا وأمريكا الجنوبية تستضيف كأس العالم؟",
      ["South Korea", "South Africa", "Japan", "Mexico"],
      ["كوريا الجنوبية", "جنوب أفريقيا", "اليابان", "المكسيك"], 3,
      type="text", difficulty="hard", category="records",
      explanation_ar="المكسيك استضافت عام ١٩٧٠، وهي خارج أوروبا/أمريكا الجنوبية."),
    q("How many goals did Just Fontaine score in 1958 (single edition record)?",
      "كم هدفاً سجل جوست فونتين في مونديال ١٩٥٨ (رقم قياسي لنسخة واحدة)؟",
      ["8", "10", "13", "15"],
      ["٨", "١٠", "١٣", "١٥"], 2,
      type="text", difficulty="hard", category="records",
      explanation_ar="١٣ هدفاً في بطولة واحدة، رقم قياسي لا يزال صامداً."),

    # ===== IMAGE: PLAYER FACE (Wikipedia photos as «covered face» style; the front-end blurs/pixelates) =====
    q("Who is this legendary player?",
      "من هذا اللاعب الأسطوري؟",
      ["Pelé", "Diego Maradona", "Romário", "Zico"],
      ["بيليه", "دييغو مارادونا", "روماريو", "زيكو"], 1,
      type="image_face", image_url=P["maradona"], difficulty="medium", category="players",
      explanation_ar="مارادونا، أسطورة الأرجنتين وقائد فريقها للقب ١٩٨٦."),
    q("Identify this player (face hidden):",
      "حدد هذا اللاعب (الوجه مغطى):",
      ["Pelé", "Garrincha", "Romário", "Ronaldo"],
      ["بيليه", "غارينشا", "روماريو", "رونالدو"], 0,
      type="image_face", image_url=P["pele"], difficulty="medium", category="players"),
    q("Which French legend is this?",
      "أي أسطورة فرنسية هذه؟",
      ["Thierry Henry", "Michel Platini", "Zinedine Zidane", "Patrick Vieira"],
      ["تييري هنري", "ميشيل بلاتيني", "زين الدين زيدان", "باتريك فييرا"], 2,
      type="image_face", image_url=P["zidane"], difficulty="medium", category="players"),
    q("Who is this all-time World Cup top scorer?",
      "من هو الهداف التاريخي لكأس العالم؟",
      ["Ronaldo (BR)", "Gerd Müller", "Miroslav Klose", "Just Fontaine"],
      ["رونالدو (البرازيل)", "غيرد مولر", "ميروسلاف كلوزه", "جوست فونتين"], 2,
      type="image_face", image_url=P["klose"], difficulty="medium", category="players"),
    q("Who is this 2022 World Cup top scorer?",
      "من هذا اللاعب هداف مونديال ٢٠٢٢؟",
      ["Olivier Giroud", "Lionel Messi", "Kylian Mbappé", "Cristiano Ronaldo"],
      ["أوليفييه جيرو", "ليونيل ميسي", "كيليان مبابي", "كريستيانو رونالدو"], 2,
      type="image_face", image_url=P["mbappe"], difficulty="medium", category="players"),
    q("Who is this striker — known as 'O Fenômeno'?",
      "من هذا المهاجم الملقّب بـ«الظاهرة»؟",
      ["Ronaldinho", "Ronaldo (Brazil)", "Romário", "Adriano"],
      ["رونالدينيو", "رونالدو (البرازيل)", "روماريو", "أدريانو"], 1,
      type="image_face", image_url=P["ronaldo_br"], difficulty="medium", category="players"),
    q("Identify this player — captained his country to World Cup glory in 2022:",
      "حدد هذا اللاعب — قاد منتخبه للقب كأس العالم ٢٠٢٢:",
      ["Ángel Di María", "Lionel Messi", "Sergio Agüero", "Rodrigo De Paul"],
      ["دي ماريا", "ليونيل ميسي", "سيرخيو أغويرو", "رودريغو دي بول"], 1,
      type="image_face", image_url=P["messi"], difficulty="medium", category="players"),
    q("Who is this Croatian legend — Golden Ball winner 2018?",
      "من هذه الأسطورة الكرواتية — فائز بالكرة الذهبية ٢٠١٨؟",
      ["Ivan Rakitić", "Luka Modrić", "Mario Mandžukić", "Ivan Perišić"],
      ["إيفان راكيتيتش", "لوكا مودريتش", "ماريو مانجوكيتش", "إيفان بيريشيتش"], 1,
      type="image_face", image_url=P["modric"], difficulty="medium", category="players"),
    q("Identify this Portuguese star with most World Cup appearances for Portugal:",
      "حدد النجم البرتغالي صاحب أكثر مشاركات في كأس العالم مع البرتغال:",
      ["Luís Figo", "Eusébio", "Cristiano Ronaldo", "Rui Costa"],
      ["لويس فيغو", "يوسيبيو", "كريستيانو رونالدو", "روي كوستا"], 2,
      type="image_face", image_url=P["cr7"], difficulty="medium", category="players"),
    q("Which Spanish midfielder (face covered)?",
      "أي لاعب وسط إسباني هذا؟",
      ["Xavi", "Iniesta", "Xabi Alonso", "Cesc Fàbregas"],
      ["تشافي", "إنييستا", "تشابي ألونسو", "فابريغاس"], 1,
      type="image_face", image_url=P["iniesta"], difficulty="medium", category="players"),
    q("Who is this goalkeeper — won World Cup 2014?",
      "من هذا الحارس — فاز بمونديال ٢٠١٤؟",
      ["Manuel Neuer", "Iker Casillas", "Hugo Lloris", "Gianluigi Buffon"],
      ["مانويل نوير", "إيكر كاسياس", "هوغو لوريس", "بوفون"], 0,
      type="image_face", image_url=P["neuer"], difficulty="medium", category="players"),
    q("Identify the Italian goalkeeper legend:",
      "حدد هذه الأسطورة الإيطالية في حراسة المرمى:",
      ["Dino Zoff", "Walter Zenga", "Gianluigi Buffon", "Salvatore Sirigu"],
      ["دينو زوف", "والتر زنغا", "جانلويجي بوفون", "سلفاتوري سيريغو"], 2,
      type="image_face", image_url=P["buffon"], difficulty="medium", category="players"),
    q("Which Brazilian Neymar plays for which clubs in his career? Identify the player:",
      "هذا اللاعب البرازيلي، من هو؟",
      ["Neymar", "Vinícius Júnior", "Rodrygo", "Antony"],
      ["نيمار", "فينيسيوس", "رودريغو", "أنتوني"], 0,
      type="image_face", image_url=P["neymar"], difficulty="medium", category="players"),
    q("Identify this English captain striker:",
      "حدد المهاجم وقائد منتخب إنجلترا هذا:",
      ["Wayne Rooney", "Harry Kane", "Jamie Vardy", "Raheem Sterling"],
      ["واين روني", "هاري كين", "جيمي فاردي", "ستيرلينغ"], 1,
      type="image_face", image_url=P["kane"], difficulty="medium", category="players"),
    q("Who is this Egyptian star?",
      "من هذا النجم المصري؟",
      ["Mohamed Salah", "Ahmed Hegazi", "Mohamed Elneny", "Trezeguet"],
      ["محمد صلاح", "أحمد حجازي", "محمد النني", "تريزيغيه"], 0,
      type="image_face", image_url=P["salah"], difficulty="medium", category="players"),
    q("Identify the Ivorian striker (former Chelsea):",
      "حدد المهاجم الإيفواري (تشيلسي سابقاً):",
      ["Yaya Touré", "Didier Drogba", "Salomon Kalou", "Wilfried Bony"],
      ["يايا توريه", "ديدييه دروغبا", "سالومون كالو", "ويلفريد بوني"], 1,
      type="image_face", image_url=P["drogba"], difficulty="medium", category="players"),
    q("Who is this Polish striker known for goal-scoring records?",
      "من هذا المهاجم البولندي الشهير بالأرقام التهديفية؟",
      ["Robert Lewandowski", "Arkadiusz Milik", "Krzysztof Piątek", "Jakub Błaszczykowski"],
      ["روبرت ليفاندوفسكي", "أركاديوش ميليك", "كريستوف بياتيك", "بلاشتشيكوفسكي"], 0,
      type="image_face", image_url=P["lewandowski"], difficulty="medium", category="players"),
    q("Identify this German legend — captain & manager who lifted the trophy:",
      "حدد هذه الأسطورة الألمانية — قائد ومدرّب رفع الكأس:",
      ["Lothar Matthäus", "Franz Beckenbauer", "Gerd Müller", "Uwe Seeler"],
      ["لوتار ماتيوس", "فرانز بيكنباور", "غيرد مولر", "أوي زيلر"], 1,
      type="image_face", image_url=P["beckenbauer"], difficulty="hard", category="players",
      explanation_ar="بيكنباور: قائد ألمانيا الفائز ١٩٧٤ ومدرّبها الفائز ١٩٩٠."),
    q("Which English striker scored the famous solo goal vs Argentina 1998?",
      "أي مهاجم إنجليزي سجل هدفاً فردياً شهيراً ضد الأرجنتين ١٩٩٨؟",
      ["Alan Shearer", "Michael Owen", "Andrew Cole", "Teddy Sheringham"],
      ["آلان شيرر", "مايكل أوين", "أندي كول", "تيدي شيرنغهام"], 1,
      type="image_face", image_url=P["owen"], difficulty="hard", category="players",
      explanation_ar="أوين أحرز هدفاً فردياً مذهلاً عمره ١٨ سنة في الدور الـ١٦."),
    q("Identify this Spanish defender — scored winner in UCL final 2014:",
      "حدد هذا المدافع الإسباني — صاحب هدف الفوز في نهائي دوري الأبطال ٢٠١٤:",
      ["Carles Puyol", "Gerard Piqué", "Sergio Ramos", "Jordi Alba"],
      ["كارلس بويول", "بيكيه", "سيرخيو راموس", "جوردي ألبا"], 2,
      type="image_face", image_url=P["ramos"], difficulty="hard", category="players"),
    q("Who is this Uruguayan striker — controversial moments in 2010 & 2014?",
      "من هذا المهاجم الأوروغواياني صاحب اللحظات الجدلية في ٢٠١٠ و٢٠١٤؟",
      ["Edinson Cavani", "Diego Forlán", "Luis Suárez", "Diego Godín"],
      ["كافاني", "ديغو فورلان", "لويس سواريز", "ديغو غودين"], 2,
      type="image_face", image_url=P["suarez"], difficulty="medium", category="players",
      explanation_ar="سواريز: حادثة اليد ضد غانا ٢٠١٠، والعض ٢٠١٤."),

    # ===== IMAGE: TROPHIES =====
    q("What is the name of the current FIFA World Cup trophy?",
      "ما اسم كأس العالم الحالية لـ FIFA؟",
      ["Jules Rimet Trophy", "FIFA World Cup Trophy", "Coupe du Monde", "Henri Delaunay Trophy"],
      ["كأس جول ريميه", "كأس العالم FIFA", "كأس العالم", "كأس هنري ديلوني"], 1,
      type="image_trophy", image_url=P["trophy"], difficulty="medium", category="tournaments",
      explanation_ar="الكأس الحالية صممها سيلفيو غازانيغا وتُمنح منذ ١٩٧٤."),
    q("Which trophy did Brazil keep permanently after winning 3 times by 1970?",
      "أي كأس احتفظت بها البرازيل بشكل دائم بعد الفوز ٣ مرات في ١٩٧٠؟",
      ["FIFA World Cup Trophy", "Jules Rimet Trophy", "Coupe Henri Delaunay", "Mitropa Cup"],
      ["كأس العالم FIFA", "كأس جول ريميه", "كأس هنري ديلوني", "كأس ميتروبا"], 1,
      type="image_trophy", image_url=P["jules_rimet"], difficulty="hard", category="tournaments",
      explanation_ar="بحسب قاعدة جول ريميه، احتفظت البرازيل بالكأس بعد فوزها الثالث."),

    # ===== HARD - DEEP TRIVIA =====
    q("Which player scored in 4 different World Cups (1998-2014)?",
      "أي لاعب سجّل في ٤ نسخ مختلفة من كأس العالم (١٩٩٨-٢٠١٤)؟",
      ["Pelé", "Cristiano Ronaldo", "Miroslav Klose", "Cuauhtémoc Blanco"],
      ["بيليه", "رونالدو", "كلوزه", "كواهتيموك بلانكو"], 2,
      type="text", difficulty="hard", category="players"),
    q("Which World Cup introduced yellow & red cards?",
      "أي نسخة من كأس العالم شهدت إدخال البطاقتين الصفراء والحمراء؟",
      ["1966", "1970", "1974", "1978"],
      ["١٩٦٦", "١٩٧٠", "١٩٧٤", "١٩٧٨"], 1,
      type="text", difficulty="hard", category="records",
      explanation_ar="استُحدثت البطاقتان في مونديال المكسيك ١٩٧٠."),
    q("Which African nation was first to reach the World Cup quarter-finals?",
      "أي منتخب أفريقي وصل إلى ربع نهائي كأس العالم لأول مرة؟",
      ["Nigeria", "Senegal", "Cameroon", "Ghana"],
      ["نيجيريا", "السنغال", "الكاميرون", "غانا"], 2,
      type="text", difficulty="hard", category="tournaments",
      explanation_ar="الكاميرون عام ١٩٩٠ بقيادة روجيه ميلا."),
    q("Which Asian nation reached the World Cup semi-finals?",
      "أي منتخب آسيوي وصل إلى نصف نهائي كأس العالم؟",
      ["Japan", "South Korea", "Saudi Arabia", "Iran"],
      ["اليابان", "كوريا الجنوبية", "السعودية", "إيران"], 1,
      type="text", difficulty="medium", category="tournaments",
      explanation_ar="كوريا الجنوبية عام ٢٠٠٢ على أرضها."),
    q("Saudi Arabia famously beat which world champion in the 2022 group stage?",
      "السعودية فازت على أي بطل عالم في دور المجموعات ٢٠٢٢؟",
      ["France", "Germany", "Argentina", "Brazil"],
      ["فرنسا", "ألمانيا", "الأرجنتين", "البرازيل"], 2,
      type="text", difficulty="medium", category="tournaments",
      explanation_ar="السعودية فازت على الأرجنتين ٢-١ — أعظم لحظات الكرة السعودية."),
    q("In which World Cup did Saudi Arabia make their first appearance?",
      "في أي مونديال شارك المنتخب السعودي لأول مرة؟",
      ["1990", "1994", "1998", "2002"],
      ["١٩٩٠", "١٩٩٤", "١٩٩٨", "٢٠٠٢"], 1,
      type="text", difficulty="medium", category="tournaments",
      explanation_ar="مشاركة السعودية الأولى كانت في مونديال أمريكا ١٩٩٤ ووصلت لدور الـ١٦."),
    q("Who scored the iconic 'banana free-kick' for Brazil vs USA, USA Cup 1997 (relevant to WC players)?",
      "من سجل الركلة الحرة الموزية الشهيرة لروبرتو كارلوس ضد فرنسا؟",
      ["Rivaldo", "Roberto Carlos", "Cafu", "Ronaldinho"],
      ["ريفالدو", "روبرتو كارلوس", "كافو", "رونالدينيو"], 1,
      type="text", difficulty="hard", category="players"),
    q("Which player has the most yellow cards in WC history?",
      "أي لاعب يحمل أكثر بطاقات صفراء في تاريخ كأس العالم؟",
      ["Maradona", "Cafu", "Andoni Goikoetxea", "Lionel Messi"],
      ["مارادونا", "كافو", "غويكوتشيا", "ميسي"], 1,
      type="text", difficulty="hard", category="records",
      explanation_ar="كافو أكثر اللاعبين تلقياً للبطاقات الصفراء في كأس العالم."),
    q("Who scored the 'Goal of the Century' vs England in 1986?",
      "من سجل «هدف القرن» ضد إنجلترا عام ١٩٨٦؟",
      ["Diego Maradona", "Mario Kempes", "Jorge Burruchaga", "Daniel Passarella"],
      ["مارادونا", "كيمبس", "بوروتشاغا", "باساريلا"], 0,
      type="text", difficulty="medium", category="players",
      explanation_ar="مارادونا تجاوز ٥ لاعبين قبل تسجيل الهدف في نفس مباراة «يد الله»."),
    q("Which World Cup featured the first penalty shoot-out?",
      "أي بطولة شهدت أول ركلات ترجيح؟",
      ["1978", "1982", "1986", "1990"],
      ["١٩٧٨", "١٩٨٢", "١٩٨٦", "١٩٩٠"], 1,
      type="text", difficulty="hard", category="records",
      explanation_ar="مونديال ١٩٨٢ — أول ركلات ترجيح في نصف النهائي بين ألمانيا الغربية وفرنسا."),
    q("Which country has appeared in every World Cup?",
      "أي منتخب شارك في جميع نسخ كأس العالم؟",
      ["Germany", "Italy", "Brazil", "Argentina"],
      ["ألمانيا", "إيطاليا", "البرازيل", "الأرجنتين"], 2,
      type="text", difficulty="medium", category="tournaments",
      explanation_ar="البرازيل هي الوحيدة التي شاركت في كل النسخ منذ ١٩٣٠."),
    q("Which keeper saved Messi's penalty in the 2022 final group game vs Saudi Arabia? (Trick: Messi scored)",
      "من حارس السعودية الذي تألق في مباراة الفوز التاريخي على الأرجنتين ٢٠٢٢؟",
      ["Mohammed Al-Rubaie", "Mohammed Al-Owais", "Yasser Al-Mosailem", "Waleed Abdullah"],
      ["محمد الرُّبَيْعي", "محمد العويس", "ياسر المسيليم", "وليد عبدالله"], 1,
      type="text", difficulty="hard", category="players",
      explanation_ar="محمد العويس قاد المرمى وتألق بإنقاذات حاسمة في الفوز التاريخي ٢-١."),
    q("Who scored Saudi Arabia's winning goal vs Argentina (2022)?",
      "من سجل هدف الفوز للسعودية على الأرجنتين (٢٠٢٢)؟",
      ["Saleh Al-Shehri", "Salem Al-Dawsari", "Firas Al-Buraikan", "Hattan Bahebri"],
      ["صالح الشهري", "سالم الدوسري", "فراس البريكان", "هتان باهبري"], 1,
      type="text", difficulty="medium", category="players",
      explanation_ar="سالم الدوسري بهدف رائع في الدقيقة ٥٣ ضمن فوز السعودية التاريخي ٢-١."),
    q("Which Saudi player scored the first goal vs Argentina (2022)?",
      "من سجل أول هدف للسعودية ضد الأرجنتين (٢٠٢٢)؟",
      ["Salem Al-Dawsari", "Saleh Al-Shehri", "Mohamed Kanno", "Sami Al-Najei"],
      ["سالم الدوسري", "صالح الشهري", "محمد كنّو", "سامي النجعي"], 1,
      type="text", difficulty="medium", category="players",
      explanation_ar="صالح الشهري بهدف التعادل في الدقيقة ٤٨."),
    q("Saudi Arabia hosted the 2034 World Cup announcement happened in which year?",
      "أُعلن عن استضافة السعودية لكأس العالم ٢٠٣٤ في أي سنة؟",
      ["2023", "2024", "2025", "2022"],
      ["٢٠٢٣", "٢٠٢٤", "٢٠٢٥", "٢٠٢٢"], 1,
      type="text", difficulty="hard", category="tournaments",
      explanation_ar="FIFA أعلنت رسمياً في ديسمبر ٢٠٢٤."),
    q("In which World Cup did the famous 'Battle of Bern' take place?",
      "في أي بطولة وقعت «معركة برن» الشهيرة؟",
      ["1950", "1954", "1958", "1962"],
      ["١٩٥٠", "١٩٥٤", "١٩٥٨", "١٩٦٢"], 1,
      type="text", difficulty="hard", category="tournaments",
      explanation_ar="مباراة المجر والبرازيل في ربع نهائي مونديال السويد ١٩٥٤."),
    q("Who was the first player to be sent off in a World Cup final?",
      "من أول لاعب طُرد في نهائي كأس العالم؟",
      ["Pedro Monzón", "Gustavo Dezotti", "Marcel Desailly", "Zinedine Zidane"],
      ["بيدرو مونزون", "ديزوتي", "ديسايي", "زيدان"], 0,
      type="text", difficulty="hard", category="records",
      explanation_ar="بيدرو مونزون (الأرجنتين) في نهائي ١٩٩٠ ضد ألمانيا."),
    q("Which World Cup featured the first video assistant referee (VAR)?",
      "أي بطولة كأس عالم استُخدم فيها حكم الفيديو المساعد (VAR) لأول مرة؟",
      ["2014", "2018", "2022", "2010"],
      ["٢٠١٤", "٢٠١٨", "٢٠٢٢", "٢٠١٠"], 1,
      type="text", difficulty="medium", category="records",
      explanation_ar="مونديال روسيا ٢٠١٨ كان أول بطولة بـ VAR."),
    q("Which player scored a hat-trick in the 2018 World Cup at age 19?",
      "أي لاعب سجل هاتريك في مونديال ٢٠١٨ وعمره ١٩ سنة؟",
      ["Kylian Mbappé", "Marcus Rashford", "Vinícius Júnior", "Phil Foden"],
      ["كيليان مبابي", "ماركوس راشفورد", "فينيسيوس", "فيل فودن"], 0,
      type="text", difficulty="hard", category="players",
      explanation_ar="مبابي ضد الأرجنتين في دور الـ١٦ بثلاثية تاريخية."),
    q("How many goals did Mbappé score in 2022 World Cup final?",
      "كم هدفاً سجل مبابي في نهائي مونديال ٢٠٢٢؟",
      ["1", "2", "3", "4"],
      ["١", "٢", "٣", "٤"], 2,
      type="text", difficulty="medium", category="players",
      explanation_ar="٣ أهداف (هاتريك في نهائي) — لكن خسرت فرنسا بركلات الترجيح."),

    # ===== JERSEY-themed (without actual jersey images — use a trophy/photo with team theme) =====
    q("Which country wears 'La Albiceleste' (white and sky-blue) jersey?",
      "أي منتخب يرتدي قميص «الألبي سيلستي» (أبيض وسماوي)؟",
      ["Uruguay", "Argentina", "Paraguay", "Greece"],
      ["الأوروغواي", "الأرجنتين", "الباراغواي", "اليونان"], 1,
      type="text", difficulty="medium", category="general"),
    q("Which country is associated with the 'Verde Amarela' (green & yellow)?",
      "أي منتخب يُعرف بـ«الفيردي أمريلا» (الأخضر والأصفر)؟",
      ["Portugal", "Brazil", "Mexico", "Cameroon"],
      ["البرتغال", "البرازيل", "المكسيك", "الكاميرون"], 1,
      type="text", difficulty="medium", category="general"),
    q("Italy's national team is nicknamed:",
      "المنتخب الإيطالي يُلقّب بـ:",
      ["Azzurri", "Furia Roja", "Tricolori", "Squadra Azurra"],
      ["أتزوري", "فوريا روخا", "تريكولوري", "سكوادرا أزورا"], 0,
      type="text", difficulty="medium", category="general",
      explanation_ar="«الأتزوري» يعني «الأزرق» باللون الرسمي للمنتخب."),
    q("England national team's nickname is:",
      "لقب المنتخب الإنجليزي هو:",
      ["The Three Lions", "The Red Devils", "The Bulldogs", "The Royals"],
      ["الأسود الثلاثة", "الشياطين الحمر", "البولدوغ", "الملكيون"], 0,
      type="text", difficulty="medium", category="general"),
    q("Germany's national team is nicknamed:",
      "المنتخب الألماني يُلقّب بـ:",
      ["Die Mannschaft", "Die Roten", "Der Adler", "Die Elf"],
      ["دي مانشافت", "دي روتن", "دير أدلر", "دي إيلف"], 0,
      type="text", difficulty="hard", category="general",
      explanation_ar="«دي مانشافت» تعني «الفريق»."),
    q("Saudi Arabia national team is nicknamed:",
      "المنتخب السعودي يُلقّب بـ:",
      ["The Falcons", "The Green Falcons", "The Eagles", "Al-Suqour"],
      ["الصقور", "الصقور الخضر", "النسور", "الصقور"], 1,
      type="text", difficulty="medium", category="general",
      explanation_ar="«الصقور الخضر» — اللقب الرسمي لمنتخبنا الوطني."),
]
